### PR TITLE
Fix cash not being always formatted

### LINKED ISSUE #100: Make it so the cash window's text is always aligned to the right
- Right now when the main text draws the cash window, it's aligned to the center

### PR DESCRIPTION
**Pull request by Lorenzooone**
Fixes #100 .

### CODE REVIEW

File: src/c/vwf.c [hunk 1]
```diff
@@ -841,6 +841,60 @@ int print_string(byte *str, int x, int y)
...
+        if(str[1] != 0xFF)
+        {
+            x += print_character(decode_character(*str++), x, y);
+            charCount++;
+        }
+        else if(str[0] == 0x5F)
+        {
+            x += str[2];
+            str += 3;
+        }
```
Comment (PhoenixBound) [inline src/c/vwf.c]: Minor thing but this acts more like 60 FF (CUSTOMCC_ADD_X) than 5F FF (CUSTOMCC_SET_X). It might be a little confusing to have 5F mean a different thing here.

Comment (Lorenzooone) [reply src/c/vwf.c]: Updated. To make it generic, it can't (in theory) access the window data to base itself off of, so initial_x is a good compromise.
